name: finance-balance-lb

services:

  postgres:
    image: postgres:18.3-alpine
    container_name: fb-lb-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'fb-db'
      POSTGRES_PASSWORD: 'fb-pwd'
    volumes:
      - ./volumes/db:/var/lib/postgresql
      - ../db-setup:/docker-entrypoint-initdb.d
    networks:
      - fb_lb_network

  fb-lb:
    image: fb-lb:multistage
    container_name: fb-lb-app
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'fb-lb-postgres'
    networks:
      - fb_lb_network

networks:
  fb_lb_network:
    driver: bridge
