name: workflow.yml

on:
  push:
    branches: [ master, develop, 'rc/**' ]
  pull_request:
    branches: [ master, develop, 'rc/**' ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '25'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle 9.7.1
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.7.1'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Generate test report with JaCoCo
        if: always()
        run: ./gradlew jacocoTestReport

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/

      - name: Calculate image name and tag based on run number and short git commit SHA
        run: |
          runNumber=${{ github.run_number }}
          shortSha=$(git rev-parse --short ${{ github.sha }})
          image="fb-lb:${runNumber}-${shortSha}"
          echo "IMAGE=$image" >> $GITHUB_ENV

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image without publication and with layers caching
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner to generate txt report
        uses: aquasecurity/trivy-action@v0.36.0
        if: always()
        with:
          scan-type: 'image'
          scan-ref: ${{ env.IMAGE }}
          severity: 'CRITICAL'
          ignore-unfixed: true
          format: 'table'
          output: trivy.txt

      - name: Upload Trivy txt report artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: trivy-report
          path: trivy.txt

      - name: Run Trivy vulnerability scanner to check quality gate
        uses: aquasecurity/trivy-action@v0.36.0
        if: always()
        with:
          scan-type: 'image'
          scan-ref: ${{ env.IMAGE }}
          severity: 'CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Run Trivy vulnerability scanner to generate SBOM CycloneDX report
        uses: aquasecurity/trivy-action@v0.36.0
        if: always()
        with:
          scan-type: 'image'
          scan-ref: ${{ env.IMAGE }}
          hide-progress: true
          format: 'cyclonedx'
          output: sbom-cyclonedx.json

      - name: Upload Trivy SBOM CycloneDX report artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: sbom-cyclonedx-report
          path: sbom-cyclonedx.json

      - name: Log in to Docker Registry
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to Docker Registry
        if: github.ref == 'refs/heads/develop'
        run: docker push ghcr.io/webdevroman/${{ env.IMAGE }}

#      - name: Push image to Docker Registry
#        if: github.ref == 'refs/heads/develop'
#        uses: docker/build-push-action@v7
#        with:
#          context: .
#          push: true
#          tags: ${{ env.IMAGE }}
